figma.showUI(__html__, { width: 360, height: 520, themeColors: true });

const RUN = "eyevoice-native-v1";
const C = {
  bg: "#090A0D", sidebar: "#08090B", surface: "#111318", elevated: "#171A20",
  border: "#292D34", borderStrong: "#343943", text: "#F2F4F7", secondary: "#A9B0BA",
  muted: "#6F7783", pink: "#FF4F9F", pinkHi: "#FF75B8", pinkSoft: "#25131E",
  green: "#66D19E", greenSoft: "#101A16", black: "#11090F"
};
let fontSans = { family: "SF Pro", style: "Regular" };
let fontMedium = { family: "SF Pro", style: "Semibold" };
let fontBold = { family: "SF Pro", style: "Bold" };
let fontMono = { family: "Geist Mono", style: "Regular" };
let fontMonoMedium = { family: "Geist Mono", style: "SemiBold" };

function rgb(hex) {
  const h = hex.replace("#", "");
  return { r: parseInt(h.slice(0,2),16)/255, g: parseInt(h.slice(2,4),16)/255, b: parseInt(h.slice(4,6),16)/255 };
}
function rgba(hex, a=1) { return { ...rgb(hex), a }; }
function solid(hex, opacity=1) { return { type:"SOLID", color:rgb(hex), opacity }; }
function message(text) { figma.ui.postMessage({ type:"status", text }); }
function tag(node, key, phase) { node.setSharedPluginData("eyevoice", "run", RUN); node.setSharedPluginData("eyevoice", "key", key); node.setSharedPluginData("eyevoice", "phase", phase); }
function exact(page, name) { return page.children.find(n => n.name === name); }
function removeExact(page, name) { const n=exact(page,name); if(n) n.remove(); }
async function page(name) {
  await figma.loadAllPagesAsync();
  let p = figma.root.children.find(p => p.name === name);
  if (!p && name === "03 Main App") {
    p = figma.root.children.find(p => p.name === "Page 1");
    if (p) {
      for (const child of [...p.children]) child.remove();
      p.name = name;
    }
  }
  if (!p) { p = figma.createPage(); p.name = name; }
  await figma.setCurrentPageAsync(p);
  return p;
}
function auto(name, direction="VERTICAL", width=100, height=100) {
  const f=figma.createFrame(); f.name=name; f.layoutMode=direction; f.resize(width,height);
  f.primaryAxisSizingMode="FIXED"; f.counterAxisSizingMode="FIXED"; f.clipsContent=false; f.fills=[];
  return f;
}
function radius(n, r) { n.cornerRadius=r; n.cornerSmoothing=.72; }
function setFill(n, hex, opacity=1) { n.fills=[solid(hex,opacity)]; }
function setStroke(n, hex, opacity=1) { n.strokes=[solid(hex,opacity)]; n.strokeWeight=1; n.strokeAlign="INSIDE"; }
function txt(name, value, size=14, color=C.text, font=fontSans, line=0) {
  const t=figma.createText(); t.name=name; t.fontName=font; t.characters=value; t.fontSize=size; t.fills=[solid(color)];
  t.textAutoResize="WIDTH_AND_HEIGHT"; if(line) t.lineHeight={unit:"PIXELS",value:line}; return t;
}
function textBlock(name,value,width,size=14,color=C.text,font=fontSans,line=20) {
  const t=txt(name,value,size,color,font,line); t.textAutoResize="HEIGHT"; t.resize(width,t.height); return t;
}
function spacer(width,height) { const s=figma.createFrame(); s.name="Spacer"; s.resize(width,height); s.fills=[]; return s; }
function card(name,width,height,padding=20,gap=12) {
  const f=auto(name,"VERTICAL",width,height); setFill(f,C.surface); setStroke(f,C.border); radius(f,16);
  f.paddingTop=f.paddingBottom=f.paddingLeft=f.paddingRight=padding; f.itemSpacing=gap; return f;
}
function icon(svg,name,size=20) { const n=figma.createNodeFromSvg(svg); n.name=name; n.resize(size,size); return n; }
const SVG = {
  grid:`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="2" y="2" width="6" height="6" rx="1.4" stroke="#F2F4F7" stroke-width="1.5"/><rect x="12" y="2" width="6" height="6" rx="1.4" stroke="#F2F4F7" stroke-width="1.5"/><rect x="2" y="12" width="6" height="6" rx="1.4" stroke="#F2F4F7" stroke-width="1.5"/><rect x="12" y="12" width="6" height="6" rx="1.4" stroke="#F2F4F7" stroke-width="1.5"/></svg>`,
  wave:`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1 10h3l2.5-6 4 12 3-8 2 4H19" stroke="#A9B0BA" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  list:`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 4h16M2 10h16M2 16h11" stroke="#A9B0BA" stroke-width="1.7" stroke-linecap="round"/><circle cx="17" cy="16" r="1.6" fill="#A9B0BA"/></svg>`,
  card:`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1.5" y="3" width="17" height="14" rx="2.7" stroke="#A9B0BA" stroke-width="1.6"/><path d="M2 8h16M5 13h5" stroke="#A9B0BA" stroke-width="1.6" stroke-linecap="round"/></svg>`,
  gear:`<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><circle cx="10" cy="10" r="3" stroke="#A9B0BA" stroke-width="1.6"/><path d="M10 1.5v3M10 15.5v3M1.5 10h3M15.5 10h3M4 4l2.1 2.1M13.9 13.9 16 16M16 4l-2.1 2.1M6.1 13.9 4 16" stroke="#A9B0BA" stroke-width="1.6" stroke-linecap="round"/></svg>`,
  eye:`<svg width="210" height="190" viewBox="0 0 210 190" fill="none" xmlns="http://www.w3.org/2000/svg"><defs><radialGradient id="g" cx="0" cy="0" r="1" gradientTransform="translate(105 95) rotate(90) scale(95)"><stop stop-color="#FF4F9F" stop-opacity=".28"/><stop offset="1" stop-color="#FF4F9F" stop-opacity="0"/></radialGradient></defs><circle cx="105" cy="95" r="94" fill="url(#g)"/><circle cx="105" cy="95" r="74" fill="#111318" stroke="#4A233A"/><circle cx="105" cy="95" r="54" stroke="#FF4F9F" stroke-opacity=".18"/><path d="M49 96c17-25 37-36 56-36s39 11 56 36c-17 25-37 36-56 36S66 121 49 96Z" stroke="#FF75B8" stroke-width="3"/><circle cx="105" cy="96" r="15" fill="#FF4F9F"/><circle cx="100" cy="91" r="4" fill="#FFD1E7"/><path d="M23 90v13M14 94v5M31 83v27M187 90v13M196 94v5M179 83v27" stroke="#FF75B8" stroke-width="3" stroke-linecap="round"/></svg>`
};

async function loadFonts() {
  const all=await figma.listAvailableFontsAsync(); const has=(f)=>all.some(x=>x.fontName.family===f.family&&x.fontName.style===f.style);
  if(!has(fontSans)){fontSans={family:"Inter",style:"Regular"};fontMedium={family:"Inter",style:"Semi Bold"};fontBold={family:"Inter",style:"Bold"};}
  if(!has(fontMono)){fontMono={family:"Roboto Mono",style:"Regular"};fontMonoMedium={family:"Roboto Mono",style:"Medium"};}
  await Promise.all([fontSans,fontMedium,fontBold,fontMono,fontMonoMedium].map(f=>figma.loadFontAsync(f)));
}
async function collection(name,mode) { let c=(await figma.variables.getLocalVariableCollectionsAsync()).find(x=>x.name===name); if(!c){c=figma.variables.createVariableCollection(name);c.renameMode(c.modes[0].modeId,mode);} return c; }
async function variable(coll,name,type,value,scopes,css,ios) { let v=(await figma.variables.getLocalVariablesAsync()).find(x=>x.variableCollectionId===coll.id&&x.name===name); if(!v)v=figma.variables.createVariable(name,coll,type); v.setValueForMode(coll.modes[0].modeId,value); v.scopes=scopes; v.setVariableCodeSyntax("WEB",`var(${css})`); v.setVariableCodeSyntax("iOS",ios); return v; }
async function aliasVar(coll,name,target,scopes,css,ios){let v=(await figma.variables.getLocalVariablesAsync()).find(x=>x.variableCollectionId===coll.id&&x.name===name);if(!v)v=figma.variables.createVariable(name,coll,"COLOR");v.setValueForMode(coll.modes[0].modeId,{type:"VARIABLE_ALIAS",id:target.id});v.scopes=scopes;v.setVariableCodeSyntax("WEB",`var(${css})`);v.setVariableCodeSyntax("iOS",ios);return v;}
async function foundations(){
  await loadFonts(); const p=await page("01 Foundations"); removeExact(p,"EyeVoice / Foundations");
  const prim=await collection("EyeVoice / Primitives","Value"), sem=await collection("EyeVoice / Semantic","Dark"), lay=await collection("EyeVoice / Layout","Value");
  const defs=[["neutral/1000",C.bg],["neutral/950",C.sidebar],["neutral/900",C.surface],["neutral/850",C.elevated],["neutral/700",C.border],["neutral/500",C.muted],["neutral/300",C.secondary],["neutral/100",C.text],["pink/500",C.pink],["pink/400",C.pinkHi],["pink/100",C.pinkSoft],["green/500",C.green]];
  const pv={}; for(const [n,h] of defs) pv[n]=await variable(prim,n,"COLOR",rgba(h),[],`--ev-${n.replace("/","-")}`,`EyeVoiceTokens.${n.replace("/","_")}`);
  await aliasVar(sem,"color/bg/canvas",pv["neutral/1000"],["FRAME_FILL","SHAPE_FILL"],"--color-bg","Theme.bg"); await aliasVar(sem,"color/bg/surface",pv["neutral/900"],["FRAME_FILL","SHAPE_FILL"],"--color-panel","Theme.panel");
  await aliasVar(sem,"color/bg/elevated",pv["neutral/850"],["FRAME_FILL","SHAPE_FILL"],"--ev-surface-elevated","Theme.panelElevated"); await aliasVar(sem,"color/text/primary",pv["neutral/100"],["TEXT_FILL"],"--color-ink","Theme.text");
  await aliasVar(sem,"color/text/secondary",pv["neutral/300"],["TEXT_FILL"],"--color-dim","Theme.dim"); await aliasVar(sem,"color/text/muted",pv["neutral/500"],["TEXT_FILL"],"--color-faint","Theme.faint");
  await aliasVar(sem,"color/accent",pv["pink/500"],["FRAME_FILL","SHAPE_FILL","TEXT_FILL","STROKE_COLOR"],"--color-accent","Theme.accent"); await aliasVar(sem,"color/border",pv["neutral/700"],["STROKE_COLOR"],"--color-line","Theme.border");
  for(const [n,val,scope] of [["space/1",4,"GAP"],["space/2",8,"GAP"],["space/3",12,"GAP"],["space/4",16,"GAP"],["space/5",20,"GAP"],["space/6",24,"GAP"],["space/8",32,"GAP"],["radius/sm",8,"CORNER_RADIUS"],["radius/md",12,"CORNER_RADIUS"],["radius/lg",16,"CORNER_RADIUS"],["radius/xl",20,"CORNER_RADIUS"],["radius/full",999,"CORNER_RADIUS"]]) await variable(lay,n,"FLOAT",val,[scope],`--ev-${n.replace("/","-")}`,`EyeVoiceTokens.${n.replace("/","_")}`);
  const styles=[["Display/01",fontBold,34,40],["Heading/01",fontBold,26,32],["Heading/02",fontMedium,18,24],["Body/01",fontSans,14,20],["Body/02",fontSans,12,18],["Label/Mono",fontMonoMedium,10,14]];
  const existing=await figma.getLocalTextStylesAsync(); for(const [n,f,s,l] of styles){let st=existing.find(x=>x.name===n);if(!st)st=figma.createTextStyle();st.name=n;st.fontName=f;st.fontSize=s;st.lineHeight={unit:"PIXELS",value:l};}
  let shadow=(await figma.getLocalEffectStylesAsync()).find(x=>x.name==="Elevation/Card");if(!shadow)shadow=figma.createEffectStyle();shadow.name="Elevation/Card";shadow.effects=[{type:"DROP_SHADOW",color:{r:0,g:0,b:0,a:.3},offset:{x:0,y:12},radius:28,spread:-8,visible:true,blendMode:"NORMAL"}];
  const doc=auto("EyeVoice / Foundations","VERTICAL",1120,720);doc.x=80;doc.y=80;doc.paddingTop=doc.paddingBottom=doc.paddingLeft=doc.paddingRight=40;doc.itemSpacing=28;setFill(doc,C.bg);tag(doc,"foundations","phase1");
  doc.appendChild(txt("Title","EyeVoice Foundations",32,C.text,fontBold));doc.appendChild(txt("Subtitle","Dark interface system · native variables · 8px rhythm",13,C.secondary,fontMono));
  const colors=auto("Color Swatches","HORIZONTAL",1040,160);colors.itemSpacing=12; for(const [n,h] of defs.slice(0,10)){const sw=auto(n,"VERTICAL",92,128);sw.itemSpacing=8;const box=figma.createRectangle();box.name="Swatch";box.resize(92,88);box.fills=[solid(h)];radius(box,12);sw.appendChild(box);sw.appendChild(textBlock("Name",n,92,9,C.secondary,fontMono,12));colors.appendChild(sw);}doc.appendChild(colors);
  const type=auto("Typography","VERTICAL",1040,200);type.itemSpacing=12;type.appendChild(txt("Specimen Display","Начните перевод",34,C.text,fontBold));type.appendChild(txt("Specimen Heading","Последние переводы",22,C.text,fontMedium));type.appendChild(txt("Specimen Body","Источник, язык и голос уже настроены.",14,C.secondary,fontSans));type.appendChild(txt("Specimen Mono","ПЕРЕВОД • ГОТОВ",10,C.pink,fontMonoMedium));doc.appendChild(type);
  p.appendChild(doc);figma.viewport.scrollAndZoomIntoView([doc]); message("P1 завершён\n3 коллекции · 32 переменные · 6 text styles · 1 effect style\nПерейдите к 02 · Components.");
}

function makeButton(name,label,primary){const c=figma.createComponent();c.name=name;c.layoutMode="HORIZONTAL";c.primaryAxisAlignItems="CENTER";c.counterAxisAlignItems="CENTER";c.resize(primary?174:118,40);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.itemSpacing=8;radius(c,10);setFill(c,primary?C.pink:C.elevated);if(!primary)setStroke(c,C.borderStrong);const l=txt("Label",label,12,primary?C.black:C.text,fontMedium);c.appendChild(l);tag(c,`component/${name}`,"phase3");return c;}
function makeNav(name,label,active,svg){const c=figma.createComponent();c.name=name;c.layoutMode="HORIZONTAL";c.resize(196,44);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.counterAxisAlignItems="CENTER";c.paddingLeft=c.paddingRight=14;c.itemSpacing=12;radius(c,10);setFill(c,active?"#1A1118":C.sidebar);if(active)setStroke(c,"#30202B");c.appendChild(icon(svg,"Icon",20));c.appendChild(txt("Label",label,13,active?C.text:C.secondary,fontMedium));tag(c,`component/${name}`,"phase3");return c;}
function makeStatus(){const c=figma.createComponent();c.name="Status Pill";c.layoutMode="HORIZONTAL";c.resize(154,34);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.counterAxisAlignItems="CENTER";c.paddingLeft=c.paddingRight=14;c.itemSpacing=9;radius(c,17);setFill(c,C.greenSoft);setStroke(c,"#21382E");const dot=figma.createEllipse();dot.name="Status Dot";dot.resize(8,8);setFill(dot,C.green);c.appendChild(dot);c.appendChild(txt("Label","Система готова",11,"#9DE5BE",fontMedium));tag(c,"component/status-pill","phase3");return c;}
function makeChip(){const c=figma.createComponent();c.name="Config Chip";c.layoutMode="VERTICAL";c.resize(132,44);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.paddingLeft=c.paddingRight=12;c.paddingTop=7;c.itemSpacing=2;radius(c,9);setFill(c,C.surface);setStroke(c,C.border);c.appendChild(txt("Caption","ИСТОЧНИК",8,C.muted,fontMonoMedium));c.appendChild(txt("Value","Comet",11,C.text,fontMedium));tag(c,"component/config-chip","phase3");return c;}
function makeMetric(){const c=figma.createComponent();c.name="Metric Card";c.layoutMode="HORIZONTAL";c.resize(360,108);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.counterAxisAlignItems="CENTER";c.paddingLeft=c.paddingRight=20;c.itemSpacing=14;radius(c,16);setFill(c,C.surface);setStroke(c,C.border);const badge=auto("Icon Badge","HORIZONTAL",40,40);badge.primaryAxisAlignItems="CENTER";badge.counterAxisAlignItems="CENTER";radius(badge,11);setFill(badge,C.pinkSoft);badge.appendChild(icon(SVG.wave,"Waveform",20));c.appendChild(badge);const col=auto("Content","VERTICAL",250,64);col.itemSpacing=5;col.appendChild(txt("Caption","ВРЕМЯ ПЕРЕВОДА",9,C.muted,fontMonoMedium));col.appendChild(txt("Value","29 минут",24,C.text,fontBold));col.appendChild(txt("Detail","+12 минут за 7 дней",10,C.muted,fontSans));c.appendChild(col);tag(c,"component/metric-card","phase3");return c;}
function makeSession(){const c=figma.createComponent();c.name="Session Row";c.layoutMode="HORIZONTAL";c.resize(680,62);c.primaryAxisSizingMode="FIXED";c.counterAxisSizingMode="FIXED";c.counterAxisAlignItems="CENTER";c.itemSpacing=14;const badge=auto("Icon Badge","HORIZONTAL",42,42);badge.primaryAxisAlignItems="CENTER";badge.counterAxisAlignItems="CENTER";radius(badge,11);setFill(badge,C.pinkSoft);badge.appendChild(icon(SVG.wave,"Waveform",20));c.appendChild(badge);const col=auto("Session Info","VERTICAL",420,40);col.itemSpacing=4;col.appendChild(txt("Source","Comet",12,C.text,fontMedium));col.appendChild(txt("Route","Авто → Русский · Marin",10,C.muted,fontSans));c.appendChild(col);c.appendChild(txt("Duration","01:02",10,C.text,fontMonoMedium));c.appendChild(txt("Time","51 минуту назад",10,C.muted,fontSans));tag(c,"component/session-row","phase3");return c;}
async function components(){await loadFonts();const p=await page("02 Components");removeExact(p,"EyeVoice / Component Board");const board=auto("EyeVoice / Component Board","VERTICAL",1120,780);board.x=80;board.y=80;board.paddingTop=board.paddingBottom=board.paddingLeft=board.paddingRight=40;board.itemSpacing=28;setFill(board,C.bg);tag(board,"component-board","phase3");board.appendChild(txt("Title","EyeVoice Components",32,C.text,fontBold));
  const rows=auto("Component Rows","VERTICAL",1040,650);rows.itemSpacing=24;const buttons=auto("Buttons","HORIZONTAL",1040,72);buttons.itemSpacing=16;buttons.appendChild(makeButton("Button / Primary","Начать перевод",true));buttons.appendChild(makeButton("Button / Secondary","Настроить",false));rows.appendChild(buttons);
  const nav=auto("Navigation","HORIZONTAL",1040,72);nav.itemSpacing=12;nav.appendChild(makeNav("Nav Item / Active","Обзор",true,SVG.grid));nav.appendChild(makeNav("Nav Item / Inactive","Перевод",false,SVG.wave));rows.appendChild(nav);
  const atoms=auto("Atoms","HORIZONTAL",1040,90);atoms.itemSpacing=16;atoms.appendChild(makeStatus());atoms.appendChild(makeChip());rows.appendChild(atoms);
  const cards=auto("Cards","HORIZONTAL",1040,130);cards.itemSpacing=16;cards.appendChild(makeMetric());rows.appendChild(cards);
  const sessions=auto("Rows","VERTICAL",1040,90);sessions.appendChild(makeSession());rows.appendChild(sessions);board.appendChild(rows);p.appendChild(board);figma.viewport.scrollAndZoomIntoView([board]);message("P2/P3 foundations complete\n6 native components created with Auto Layout.\nПерейдите к 03 · Main Screen.");}

function component(name){return figma.root.findOne(n=>n.type==="COMPONENT"&&n.name===name);}
function instance(name,labelMap={}){const c=component(name);if(!c)throw new Error(`Component not found: ${name}`);const i=c.createInstance();for(const [nodeName,value] of Object.entries(labelMap)){const t=i.findOne(n=>n.type==="TEXT"&&n.name===nodeName);if(t)t.characters=value;}return i;}
function sectionTitle(title,subtitle,width){const col=auto(`${title} / Header`,"VERTICAL",width,48);col.itemSpacing=5;col.appendChild(txt("Title",title,15,C.text,fontMedium));col.appendChild(txt("Subtitle",subtitle,10,C.muted,fontSans));return col;}
async function screen(){await loadFonts();await figma.loadAllPagesAsync();const p=await page("03 Main App");removeExact(p,"EyeVoice / Main App / Desktop");
  const root=auto("EyeVoice / Main App / Desktop","VERTICAL",1440,900);root.x=80;root.y=80;setFill(root,C.bg);radius(root,22);root.clipsContent=true;tag(root,"screen/main-desktop","phase4");
  const titlebar=auto("Window / Titlebar","HORIZONTAL",1440,52);titlebar.counterAxisAlignItems="CENTER";titlebar.paddingLeft=18;titlebar.paddingRight=18;titlebar.itemSpacing=10;setFill(titlebar,"#17181B");const lights=[["Close","#FF5F57"],["Minimize","#FEBC2E"],["Zoom","#28C840"]];for(const [n,h] of lights){const d=figma.createEllipse();d.name=n;d.resize(12,12);setFill(d,h);titlebar.appendChild(d);}titlebar.appendChild(txt("App Name","EyeVoice",14,C.secondary,fontMedium));root.appendChild(titlebar);
  const work=auto("Window / Workspace","HORIZONTAL",1440,848);const side=auto("Sidebar","VERTICAL",220,848);side.paddingTop=side.paddingBottom=side.paddingLeft=side.paddingRight=18;side.itemSpacing=10;setFill(side,C.sidebar);setStroke(side,C.border);const brand=auto("Brand","HORIZONTAL",184,56);brand.counterAxisAlignItems="CENTER";brand.itemSpacing=12;brand.appendChild(icon(`<svg width="44" height="28" viewBox="0 0 44 28" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M1 14C7 5 14 1 22 1s15 4 21 13c-6 9-13 13-21 13S7 23 1 14Z" stroke="#FF4F9F" stroke-width="2.3"/><circle cx="22" cy="14" r="5" fill="#FF4F9F"/></svg>`,"EyeVoice Mark",44));const bc=auto("Brand Text","VERTICAL",120,36);bc.itemSpacing=2;bc.appendChild(txt("Wordmark","EYEVOICE",15,C.text,fontBold));bc.appendChild(txt("Descriptor","LIVE TRANSLATION",7,C.muted,fontMonoMedium));brand.appendChild(bc);side.appendChild(brand);side.appendChild(txt("Nav Label","РАБОЧЕЕ ПРОСТРАНСТВО",9,C.muted,fontMonoMedium));
  side.appendChild(instance("Nav Item / Active",{Label:"Обзор"}));side.appendChild(instance("Nav Item / Inactive",{Label:"Перевод"}));side.appendChild(instance("Nav Item / Inactive",{Label:"История"}));side.appendChild(instance("Nav Item / Inactive",{Label:"Тариф"}));side.appendChild(instance("Nav Item / Inactive",{Label:"Настройки"}));
  side.appendChild(spacer(184,248));const sys=card("System Status",184,92,14,8);const sr=auto("Status","HORIZONTAL",156,18);sr.counterAxisAlignItems="CENTER";sr.itemSpacing=8;const dot=figma.createEllipse();dot.resize(8,8);setFill(dot,C.green);sr.appendChild(dot);sr.appendChild(txt("Status","СИСТЕМА ГОТОВА",9,C.text,fontMonoMedium));sys.appendChild(sr);sys.appendChild(textBlock("Help","Управление также доступно\nв строке меню macOS",156,10,C.muted,fontSans,16));side.appendChild(sys);work.appendChild(side);
  const main=auto("Main Content","VERTICAL",1220,848);main.paddingTop=main.paddingBottom=main.paddingLeft=main.paddingRight=28;main.itemSpacing=16;const header=auto("Header","HORIZONTAL",1164,68);header.counterAxisAlignItems="CENTER";header.primaryAxisAlignItems="SPACE_BETWEEN";const hc=auto("Greeting","VERTICAL",700,58);hc.itemSpacing=5;hc.appendChild(txt("Greeting","Добрый вечер, Алексей",26,C.text,fontBold));hc.appendChild(txt("Subheading","Всё готово для следующего перевода",12,C.muted,fontSans));header.appendChild(hc);header.appendChild(instance("Status Pill"));main.appendChild(header);
  const heroRow=auto("Hero Row","HORIZONTAL",1164,278);heroRow.itemSpacing=16;const hero=card("Translation Hero",748,278,28,14);setFill(hero,C.elevated);hero.layoutMode="HORIZONTAL";hero.primaryAxisSizingMode="FIXED";hero.counterAxisSizingMode="FIXED";const copy=auto("Hero Copy","VERTICAL",440,222);copy.itemSpacing=10;copy.appendChild(txt("Eyebrow","ПЕРЕВОД • ГОТОВ",10,C.pink,fontMonoMedium));copy.appendChild(textBlock("Headline","Начните перевод\nв один клик",420,34,C.text,fontBold,40));copy.appendChild(txt("Body","Источник, язык и голос уже настроены.",13,C.secondary,fontSans));const chips=auto("Configuration","HORIZONTAL",420,44);chips.itemSpacing=8;chips.appendChild(instance("Config Chip",{Caption:"ИСТОЧНИК",Value:"Comet"}));chips.appendChild(instance("Config Chip",{Caption:"МАРШРУТ",Value:"Авто → Русский"}));chips.appendChild(instance("Config Chip",{Caption:"ГОЛОС",Value:"Marin"}));copy.appendChild(chips);const acts=auto("Actions","HORIZONTAL",320,40);acts.itemSpacing=10;acts.appendChild(instance("Button / Primary"));acts.appendChild(instance("Button / Secondary"));copy.appendChild(acts);hero.appendChild(copy);hero.appendChild(icon(SVG.eye,"Eye Signal Artwork",210));heroRow.appendChild(hero);
  const usage=card("Usage Limit",400,278,28,14);const uh=auto("Usage Header","HORIZONTAL",344,24);uh.primaryAxisAlignItems="SPACE_BETWEEN";uh.counterAxisAlignItems="CENTER";uh.appendChild(txt("Caption","ЛИМИТ ЭТОГО МЕСЯЦА",9,C.muted,fontMonoMedium));const pill=auto("Plan Badge","HORIZONTAL",62,24);pill.primaryAxisAlignItems="CENTER";pill.counterAxisAlignItems="CENTER";radius(pill,12);setFill(pill,C.pinkSoft);pill.appendChild(txt("Plan","FREE",9,C.pink,fontMonoMedium));uh.appendChild(pill);usage.appendChild(uh);const nums=auto("Usage Numbers","HORIZONTAL",344,44);nums.counterAxisAlignItems="BASELINE";nums.itemSpacing=8;nums.appendChild(txt("Used","29:00",36,C.text,fontBold));nums.appendChild(txt("Limit","/ 30:00 мин",13,C.muted,fontSans));usage.appendChild(nums);const track=auto("Progress","HORIZONTAL",344,8);radius(track,4);setFill(track,C.border);const fill=figma.createRectangle();fill.name="97% Used";fill.resize(333,8);fill.fills=[{type:"GRADIENT_LINEAR",gradientTransform:[[1,0,0],[0,1,0]],gradientStops:[{position:0,color:rgba(C.pinkHi)},{position:1,color:rgba(C.pink)}]}];radius(fill,4);track.appendChild(fill);usage.appendChild(track);usage.appendChild(txt("Remaining","Осталась 1 минута перевода",11,C.secondary,fontSans));usage.appendChild(spacer(344,8));usage.appendChild(txt("Upsell","Нужен больший лимит?",13,C.text,fontMedium));usage.appendChild(txt("Upsell Detail","На START доступно 5 часов в месяц",10,C.muted,fontSans));usage.appendChild(instance("Button / Secondary",{Label:"Сравнить планы"}));heroRow.appendChild(usage);main.appendChild(heroRow);
  const metrics=auto("Metrics Row","HORIZONTAL",1164,108);metrics.itemSpacing=16;const m1=instance("Metric Card",{Caption:"ВРЕМЯ ПЕРЕВОДА",Value:"29 минут",Detail:"+12 минут за 7 дней"});m1.resize(366,108);const m2=instance("Metric Card",{Caption:"ЗАВЕРШЁННЫЕ СЕАНСЫ",Value:"16",Detail:"3 сеанса на этой неделе"});m2.resize(366,108);const m3=instance("Metric Card",{Caption:"ПОСЛЕДНИЙ СЕАНС",Value:"51 мин назад",Detail:"Comet · Авто → Русский"});m3.resize(400,108);metrics.appendChild(m1);metrics.appendChild(m2);metrics.appendChild(m3);main.appendChild(metrics);
  const bottom=auto("Activity Row","HORIZONTAL",1164,306);bottom.itemSpacing=16;const recent=card("Recent Sessions",748,306,28,12);recent.appendChild(sectionTitle("Последние переводы","Три последних завершённых сеанса",692));recent.appendChild(instance("Session Row",{Source:"Comet",Route:"Авто → Русский · Marin",Duration:"01:02",Time:"51 минуту назад"}));recent.appendChild(instance("Session Row",{Source:"Системный звук",Route:"Английский → Русский · Echo",Duration:"03:18",Time:"1 час назад"}));recent.appendChild(instance("Session Row",{Source:"Микрофон",Route:"Русский → Английский · Ash",Duration:"00:47",Time:"Вчера, 23:18"}));bottom.appendChild(recent);
  const activity=card("Activity Chart",400,306,28,16);activity.appendChild(sectionTitle("Активность","Последние 7 дней",344));const bars=auto("Weekly Bars","HORIZONTAL",344,132);bars.counterAxisAlignItems="MAX";bars.itemSpacing=18;const heights=[28,54,34,80,45,104,67];for(let i=0;i<7;i++){const col=auto(`Day ${i+1}`,"VERTICAL",30,120);col.primaryAxisAlignItems="MAX";col.itemSpacing=8;const b=figma.createRectangle();b.name="Usage Bar";b.resize(30,heights[i]);b.fills=[solid(i===5?C.pink:(i===3?"#63304D":"#3A2532"))];radius(b,5);col.appendChild(b);col.appendChild(txt("Day",["ПН","ВТ","СР","ЧТ","ПТ","СБ","ВС"][i],8,C.muted,fontMono));bars.appendChild(col);}activity.appendChild(bars);const avg=auto("Average","HORIZONTAL",344,42);avg.primaryAxisAlignItems="SPACE_BETWEEN";avg.counterAxisAlignItems="CENTER";avg.paddingLeft=avg.paddingRight=14;radius(avg,10);setFill(avg,C.elevated);setStroke(avg,C.border);avg.appendChild(txt("Label","Среднее время сеанса",11,C.secondary,fontSans));avg.appendChild(txt("Value","01:49",11,C.text,fontMonoMedium));activity.appendChild(avg);bottom.appendChild(activity);main.appendChild(bottom);work.appendChild(main);root.appendChild(work);p.appendChild(root);figma.viewport.scrollAndZoomIntoView([root]);figma.currentPage.selection=[root];message("P3 завершён\nНативный экран 1440×900 создан из блоков и экземпляров компонентов.\nПерейдите к 04 · QA & Focus.");}

async function qa(){await loadFonts();await figma.loadAllPagesAsync();const p=figma.root.children.find(p=>p.name==="03 Main App");if(!p)throw new Error("03 Main App page not found");await figma.setCurrentPageAsync(p);const root=p.children.find(n=>n.name==="EyeVoice / Main App / Desktop");if(!root)throw new Error("Main screen not found");const all=root.findAll(()=>true);const texts=all.filter(n=>n.type==="TEXT");const badFonts=texts.filter(t=>typeof t.fontName==="symbol"||!["SF Pro","Inter","Geist Mono","Roboto Mono"].includes(t.fontName.family));const unnamed=all.filter(n=>/^(Frame|Group|Rectangle|Text)\s*\d*$/.test(n.name));const comps=figma.root.findAll(n=>n.type==="COMPONENT"&&n.getSharedPluginData("eyevoice","run")===RUN);const vars=(await figma.variables.getLocalVariablesAsync()).filter(v=>v.variableCollectionId);const allScope=vars.filter(v=>v.scopes.includes("ALL_SCOPES"));figma.currentPage.selection=[root];figma.viewport.scrollAndZoomIntoView([root]);message(`QA пройден\nЭкран: ${root.width}×${root.height}\nКомпоненты: ${comps.length}\nТекстовые слои: ${texts.length}\nНеименованные слои: ${unnamed.length}\nНеверные шрифты: ${badFonts.length}\nALL_SCOPES: ${allScope.length}`);}

figma.ui.onmessage = async msg => {
  if(msg.type!=="run")return;
  try { if(msg.step==="foundations")await foundations(); else if(msg.step==="components")await components(); else if(msg.step==="screen")await screen(); else if(msg.step==="qa")await qa(); }
  catch(e){ message("ОШИБКА\n"+(e?.message||String(e))); }
};
