project_id = "seexmgivktuycodxrjhs"

[functions.realtime-token]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = true

[functions.yookassa-webhook]
verify_jwt = false

[functions.usage-balance]
verify_jwt = true

[functions.manage-subscription]
verify_jwt = true

[functions.renew-subscriptions]
verify_jwt = false
